# Generated by Django 5.0.4 on 2024-05-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Inmueble',
            new_name='inmueble',
        ),
    ]
